#ifndef CONFIGH
#define CONFIGH

#define HORIZONTAL_ACTIVE 800
#define HORIZONTAL_BLANK 20

#define VERTICAL_ACTIVE 600
#define VERTICAL_BLANK 20

#define HSYNC_WIDTH 10
#define VSYNC_WIDTH 10


#endif